version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - 4572:4572
      - 8000:8000
      - 8081:8081
    environment:
      - SERVICES=s3:4572,dynamodb:8000
      - DEFAULT_REGION=ap-south-1
      - PORT_WEB_UI=8081
